### ISSUE TITLE
.NET Standard 2.0 Support?

### ISSUE THREAD

**Issue by NightOwl888** [kurtmkurtm/LiquidTestReports#16]
I see that you changed from .NET Standard 2.0 to 2.1 in https://github.com/kurtmkurtm/LiquidTestReports/commit/1d99a300e6609e1609d3675e5aa6a8376e9e3a3d. Why was this done? I don't see any other commits that use functionality that doesn't exist in .NET Standard 2.0.

We'd like to use this library, but since we are targeting .NET Standard 2.0 (and since it doesn't require extra configuration, testing on .NET Core 2.1) it is not compatible with all of our targets. To prevent versioning conflicts, it has always been Microsoft's recommendation to target the lowest version you can when building shared libraries. On the [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target) page:

> We recommend you target the lowest version of .NET Standard possible.

Of course, .NET Standard 1.x is pretty much moot since .NET Core 1.x went out of support, but .NET Standard 2.0 is still the "standard" way that most libraries use to eliminate multi-targeting.

**Comment by kurtmkurtm** [comment]
For anyone in the future viewing this issue, please see PR discussion for details: https://github.com/kurtmkurtm/LiquidTestReports/pull/17
