### ISSUE TITLE
README: missing parameter when using LiquidTestReports.Custom NuGet

### ISSUE THREAD

**Issue by edumserrano** [kurtmkurtm/LiquidTestReports#27]
On the [README](https://github.com/kurtmkurtm/LiquidTestReports#liquidtestreportscustom), on the LiquidTestReports.Custom section, on step 3,  it says:

> 3. Run the tests using the supplied logger:
`dotnet test --logger "liquid.custom;TemplateExample.txt"`

When I tried to use the above syntax with the following command:
`dotnet test .\DotNet.Sdk.Extensions.sln --logger "liquid.custom;D:\Dev\edumserrano\dot-net-sdk-extensions\tests\liquid-test-logger-template.md"`

I got this error on the output:

> The Test Logger URI 'liquid.custom;D:\Dev\edumserrano\dot-net-sdk-extensions\tests\liquid-test-logger-template.md' is not valid.  The Test Logger will be ignored.

Looking at the code I found that the correct syntax should be:
`dotnet test .\DotNet.Sdk.Extensions.sln --logger "liquid.custom;Template=D:\Dev\edumserrano\dot-net-sdk-extensions\tests\liquid-test-logger-template.md"`

Using the above command there are no errors and the report is created successfully.

Did I miss something or should the README be updated with the correct command? 
Furthermore if you think it's worth it, I'd suggest improving the error message to give a better indication of what's wrong? People can go looking into the source code but if possible a better error message would have driven me to solve the problem quickly.

**Comment by kurtmkurtm** [comment]
Hi @edumserrano, looks like it is a mistake in the readme, your example is correct, I will update the docs. 

On the error message, unfortunately in this scenario that invalid URI message is coming from vstest, so it's not possible to change this.

**Comment by kurtmkurtm** [comment]
Thanks for your suggestion, the docs pages are now updated to include this now.
