### ISSUE TITLE
Docs: how to access test traits

### ISSUE THREAD

**Issue by edumserrano** [kurtmkurtm/LiquidTestReports#29]
Looking at the [properties that can be used in custom templates](https://github.com/kurtmkurtm/LiquidTestReports/blob/master/docs/Properties.md#run) I can see that the list of traits is available:

> traits - dictionary of traits on test case

However I had some difficulty on how to access the values for the traits. Looking at the example in the examples provided in the [properties docs](https://github.com/kurtmkurtm/LiquidTestReports/blob/master/docs/Properties.md) the usage and output are not useful as it tries to output the entire list of traits which results in a blank output.

By going through the code I found that the traits are represented by a list of [TraitDrop](https://github.com/kurtmkurtm/LiquidTestReports/blob/master/src/LiquidTestReports.Core/Drops/TraitDrop.cs) objects and then I was able to output the traits by using something like:

```
{%- for trait in result.test_case.traits -%}
[{{ trait.Name }} : {{ trait.Value }}]</br>
{%- endfor -%}
```

Perhaps it's worth improving the example in the docs for how to access traits?

**Comment by kurtmkurtm** [comment]
Thanks for your suggestion, a lot of time has gone since this was raised, but the docs have been updated to include this now.
