### ISSUE TITLE
Pass Rate 1000%

### ISSUE THREAD

**Issue by Chris-D-Turk** [kurtmkurtm/LiquidTestReports#34]
The Pass Rate on a simple .net6 project (only one nunit test) is reported as 1000% instead of 100%.
![image](https://user-images.githubusercontent.com/2423981/199508730-a07c8a4c-4c27-469d-bcd3-ec853f497472.png)

`liquid --inputs "File=TestResults/*.trx" --output-file report.md`

Is this a localization issue? e.g. 100.0% interpreted as 1000% (i'm on a german machine here)

**Comment by kurtmkurtm** [comment]
Hi, I was able to replicate this, you are correct, it's a localisation issue. 
The next update will include a fix
