### ISSUE TITLE
Add .NET 9 Support

### ISSUE THREAD

**Issue by danielcrabtree** [kurtmkurtm/LiquidTestReports#43]
Version 2.0.0-beta.2 is not working with .NET 9 RC2.  It failed to install with the error "Package liquidtestreports.cli is not a .NET tool." This is because the manifest does not list .NET 9 as supported.

Note: It was working with .NET 9 RC1 as that version was still looking for net8.0 moniker instead of net9.0.

**Comment by kurtmkurtm** [comment]
Hi, thanks for raising this. I will test this out and add support for this in the next release
